"""Compatibility entry point: ``python -m herdeck.app`` and ``from herdeck.app
import main``.

The legacy ``App`` runtime that lived here is gone; ``herdeck`` runs the one
runtime (``herdeck.host``: DeckApp + LiveSource + Orchestrator with a deck
front). This module stays so service scripts and console-script wrappers
generated by older installs (``from herdeck.app import main``) keep working.
"""

from __future__ import annotations

from .host import main

__all__ = ["main"]

if __name__ == "__main__":
    main()
